{
 "title": "Tren Kualitas Udara (Room A)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Dust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  pm25 AS \"dust Room B\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_B'\r\nORDER BY timestamp ASC"
    },
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  pm25 AS \"dust Room A\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_A'\r\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  humidity AS \"humidity Room B\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_B'\r\nORDER BY timestamp ASC"
    },
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  humidity AS \"humidity Room A\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_A'\r\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  co2 AS \"CO2 Room A\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_A'\r\nORDER BY timestamp ASC"
    },
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  co2 AS \"CO2 Room B\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_B'\r\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  temperature AS \"temperature Room B\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_B'\r\nORDER BY timestamp ASC"
    },
    {
     "dataset": "iaq_monitoring",
     "rawSql": "SELECT\r\n  timestamp - INTERVAL '7 hour' AS \"time\",\r\n  temperature AS \"temperature Room A\"\r\nFROM daily_logs\r\nWHERE room_id = 'Room_A'\r\nORDER BY timestamp ASC"
    }
   ]
  }
 ]
}